import { FieldDefinition } from "./types";

// GARAGE_001 field catalog. Business-type tags act as the "master switch":
// a field is only required when its businessTypes include the selected type
// (or "everyone", or when the type is "mixed", which includes all fields).
export const GARAGE_FIELD_DEFINITIONS: FieldDefinition[] = [
  {
    id: "business_type",
    label: "Garage business type",
    section: "business_identity",
    type: "enum",
    required: true,
    priority: 1,
    businessTypes: "everyone",
    options: [
      "dealer",
      "dealer_plus_repair",
      "repair",
      "body",
      "heavy",
      "tow",
      "parking",
      "car_wash",
      "mixed",
    ],
    description: "Primary garage operation type.",
    question:
      "First, in one line — what's the shop? Are you mainly a dealer selling cars, a repair or body shop, a tow operator, a car wash or detailer, a parking or storage lot, or some mix?",
    whyWeAsk:
      "Garage is several different businesses on one application, so this tells us which questions actually apply.",
  },
  {
    id: "business_story",
    label: "Business story",
    section: "business_identity",
    type: "string",
    required: false,
    narrative: true,
    priority: 2,
    businessTypes: "everyone",
    description: "Natural-language description of the operation.",
    question:
      "Tell me about the operation — what do you do day to day, how long have you been at it, and what's the place like?",
    whyWeAsk:
      "This creates the narrative that leads the submission and helps the underwriter understand the account.",
  },
  {
    id: "legal_name",
    label: "Legal business name",
    section: "business_identity",
    type: "string",
    required: true,
    priority: 3,
    businessTypes: "everyone",
    description: "Exact legal entity name.",
    question: "What's the legal name, and is there a different name on the sign or website?",
    whyWeAsk:
      "The policy has to be in the exact right name; mismatches can get submissions kicked back.",
  },
  {
    id: "dba_name",
    label: "DBA / trade name",
    section: "business_identity",
    type: "string",
    required: false,
    priority: 4,
    businessTypes: "everyone",
    description: "Different public-facing name, if any.",
    question: "Is there a different name on the sign, website, or Google listing?",
    whyWeAsk:
      "Underwriters verify the business online, so the submission should match what they find.",
  },
  {
    id: "entity_type",
    label: "Entity type",
    section: "business_identity",
    type: "enum",
    required: true,
    priority: 5,
    businessTypes: "everyone",
    options: ["LLC", "Corporation", "Sole proprietor", "Partnership", "Other"],
    description: "Legal structure of the business.",
    question: "Are you an LLC, a corporation, partnership, or just you as an individual?",
    whyWeAsk: "The owners and who is covered flow from how the business is set up.",
  },
  {
    id: "years_in_business",
    label: "Years in business",
    section: "business_identity",
    type: "number",
    required: true,
    priority: 6,
    businessTypes: "everyone",
    description: "How long the business has operated.",
    question: "How long have you been in business?",
    whyWeAsk: "New shops are harder to place; experience is a selling point.",
  },
  {
    id: "owner_experience_years",
    label: "Owner industry experience",
    section: "business_identity",
    type: "number",
    required: false,
    priority: 7,
    businessTypes: "everyone",
    description: "How long the owner has personally done this work.",
    question: "How long have you personally been doing this kind of work?",
    whyWeAsk: "Even if the shop is new, owner experience can help the submission.",
  },
  {
    id: "why_shopping",
    label: "Why shopping coverage now",
    section: "coverage_intent",
    type: "string",
    required: true,
    narrative: true,
    priority: 8,
    businessTypes: "everyone",
    description: "Reason for seeking coverage.",
    question:
      "What's got you shopping coverage right now — starting up, contract requirement, switching carriers, or renewal?",
    whyWeAsk: "Knowing the reason helps frame the account to the underwriter.",
  },
  {
    id: "sales_model",
    label: "Sales model",
    section: "operations",
    type: "enum",
    required: true,
    priority: 20,
    businessTypes: ["dealer", "dealer_plus_repair"],
    options: ["retail", "wholesale", "broker", "mixed"],
    description: "How the dealership sells vehicles.",
    question:
      "Are your sales mostly retail to the public, wholesale or dealer-to-dealer, or do you broker?",
    whyWeAsk:
      "Retail used-car sales are easier to place; wholesale or broker activity can change the market.",
  },
  {
    id: "vehicles_sold_per_year",
    label: "Vehicles sold per year",
    section: "operations",
    type: "number",
    required: true,
    priority: 21,
    businessTypes: ["dealer", "dealer_plus_repair"],
    description: "Annual number of vehicle sales.",
    question: "Roughly how many vehicles do you sell a year?",
    whyWeAsk: "Vehicle sales volume is a rating and underwriting basis.",
  },
  {
    id: "sales_revenue",
    label: "Annual sales revenue",
    section: "operations",
    type: "currency",
    required: true,
    priority: 22,
    businessTypes: ["dealer", "dealer_plus_repair"],
    description: "Annual revenue from vehicle sales.",
    question: "What's your annual sales revenue from vehicle sales?",
    whyWeAsk: "Revenue tells the market the size of the operation.",
  },
  {
    id: "service_repair_revenue",
    label: "Annual service / repair revenue",
    section: "operations",
    type: "currency",
    required: false,
    priority: 23,
    businessTypes: ["dealer_plus_repair", "repair", "body", "heavy", "car_wash"],
    description: "Annual revenue from service or repair work.",
    question: "What's your split between sales revenue and any service or repair revenue?",
    whyWeAsk: "Service work is rated differently than sales activity.",
  },
  {
    id: "dealer_plate_count",
    label: "Dealer plate count",
    section: "vehicles_driving",
    type: "number",
    required: true,
    priority: 24,
    businessTypes: ["dealer", "dealer_plus_repair"],
    description: "Number of dealer plates.",
    question: "How many dealer plates do you have?",
    whyWeAsk: "Dealer plates drive auto liability exposure and pricing.",
  },
  {
    id: "plates_loaned_or_rented",
    label: "Dealer plates loaned, rented, or leased out",
    section: "vehicles_driving",
    type: "boolean",
    required: true,
    priority: 25,
    businessTypes: ["dealer", "dealer_plus_repair"],
    description: "Whether plates ever leave the dealer's control.",
    question: "Do you ever lease, rent, or loan your plates to anyone?",
    whyWeAsk: "Markets generally do not like plates leaving the business's control.",
  },
  {
    id: "buy_here_pay_here",
    label: "Buy-here-pay-here financing",
    section: "operations",
    type: "boolean",
    required: true,
    priority: 26,
    businessTypes: ["dealer", "dealer_plus_repair"],
    description: "Whether dealer carries financing paper.",
    question:
      "Do you finance your own buyers — buy-here-pay-here — or do they get outside financing?",
    whyWeAsk: "Carrying the paper adds collections and repossession exposure.",
  },
  {
    id: "titles_transfer_promptly",
    label: "Titles transfer promptly",
    section: "operations",
    type: "boolean",
    required: true,
    priority: 27,
    businessTypes: ["dealer", "dealer_plus_repair"],
    description: "Whether titles transfer according to state rules.",
    question: "Do titles transfer promptly on every sale, in line with your state's rules?",
    whyWeAsk: "Clean title handling avoids E&O and regulatory issues.",
  },
  {
    id: "self_repossession",
    label: "Self repossession",
    section: "operations",
    type: "boolean",
    required: true,
    priority: 28,
    businessTypes: ["dealer", "dealer_plus_repair"],
    description: "Whether the business repossesses vehicles itself.",
    question: "Do you ever repossess vehicles yourself?",
    whyWeAsk: "Self-repossession is higher-risk and can need a different market.",
  },
  {
    id: "test_drives_allowed",
    label: "Test drives allowed",
    section: "vehicles_driving",
    type: "boolean",
    required: true,
    priority: 40,
    businessTypes: ["dealer", "dealer_plus_repair"],
    description: "Whether customers test-drive vehicles.",
    question: "Do customers test-drive vehicles?",
    whyWeAsk: "Test drives are a major auto liability and theft exposure.",
  },
  {
    id: "test_drive_license_check",
    label: "License checked before test drive",
    section: "vehicles_driving",
    type: "boolean",
    required: true,
    priority: 41,
    businessTypes: ["dealer", "dealer_plus_repair"],
    dependencies: [{ fieldId: "test_drives_allowed", operator: "equals", value: true }],
    description: "Whether license is checked before test drive.",
    question: "When a customer test-drives, do you check their license first?",
    whyWeAsk: "License checks reduce theft and accident risk.",
  },
  {
    id: "test_drive_ride_along",
    label: "Employee rides along on test drive",
    section: "vehicles_driving",
    type: "boolean",
    required: true,
    priority: 42,
    businessTypes: ["dealer", "dealer_plus_repair"],
    dependencies: [{ fieldId: "test_drives_allowed", operator: "equals", value: true }],
    description: "Whether an employee rides with the customer.",
    question: "When a customer test-drives, does someone from the business ride along?",
    whyWeAsk: "Ride-alongs reduce theft and accident risk.",
  },
  {
    id: "overnight_test_drives",
    label: "Overnight or extended test drives",
    section: "vehicles_driving",
    type: "boolean",
    required: true,
    priority: 43,
    businessTypes: ["dealer", "dealer_plus_repair"],
    dependencies: [{ fieldId: "test_drives_allowed", operator: "equals", value: true }],
    description: "Whether cars are allowed off-lot overnight.",
    question: "Do you ever let a car go overnight or for an extended test drive?",
    whyWeAsk: "Cars out overnight are a large exposure and can be difficult to place.",
  },
  {
    id: "loaner_or_rental_vehicles",
    label: "Loaner or rental vehicles",
    section: "vehicles_driving",
    type: "boolean",
    required: true,
    priority: 44,
    businessTypes: "everyone",
    description: "Whether the business loans, leases, or rents vehicles.",
    question: "Do you lease or rent vehicles to anyone, or give out loaner cars?",
    whyWeAsk:
      "Loaners and rentals put vehicles in someone else's hands and are difficult for standard markets.",
  },
  {
    id: "rideshare_use_owned_autos",
    label: "Rideshare use of owned autos",
    section: "vehicles_driving",
    type: "boolean",
    required: true,
    priority: 45,
    businessTypes: "everyone",
    description: "Whether any owned vehicle is used for Uber/Lyft/rideshare.",
    question: "Are any of the business's vehicles used for Uber, Lyft, or any rideshare?",
    whyWeAsk: "Rideshare is not ordinary garage exposure and is usually excluded.",
  },
  {
    id: "lot_security",
    label: "Lot security",
    section: "premises",
    type: "string",
    required: true,
    priority: 50,
    businessTypes: "everyone",
    description: "How the location is secured.",
    question:
      "Tell me about the lot or premises — is it fenced and gated, cameras, in a building, or open lot?",
    whyWeAsk: "Lot security affects theft exposure and garagekeepers coverage.",
  },
  {
    id: "keys_handling",
    label: "Key handling",
    section: "premises",
    type: "string",
    required: true,
    priority: 51,
    businessTypes: "everyone",
    description: "How keys are stored during and after business hours.",
    question: "How are the keys handled during business hours and after you close?",
    whyWeAsk: "Keys left in vehicles or lockboxes create theft issues.",
  },
  {
    id: "desired_liability_limits",
    label: "Desired liability limits",
    section: "coverage_intent",
    type: "string",
    required: true,
    priority: 60,
    businessTypes: "everyone",
    description: "Current or requested liability limits.",
    question: "What liability limits are you carrying now, or do you need for any contract or license?",
    whyWeAsk: "Contracts, leases, and licenses may require minimum limits.",
  },
  {
    id: "current_insurance",
    label: "Currently insured",
    section: "history",
    type: "boolean",
    required: true,
    priority: 70,
    businessTypes: "everyone",
    description: "Whether the business currently has coverage.",
    question: "Are you insured right now, and with who? Or is this your first coverage?",
    whyWeAsk: "Prior coverage gives markets confidence; no prior coverage needs explanation.",
  },
  {
    id: "current_carrier",
    label: "Current carrier",
    section: "history",
    type: "string",
    required: false,
    priority: 71,
    businessTypes: "everyone",
    description: "Current insurance carrier.",
    question: "Who is your current carrier?",
    whyWeAsk: "Current carrier context helps explain renewal or market movement.",
  },
  {
    id: "prior_losses",
    label: "Prior losses",
    section: "history",
    type: "boolean",
    required: true,
    priority: 72,
    businessTypes: "everyone",
    description: "Whether there were claims or losses in the last three years.",
    question: "In the last three years, any claims or losses — even small ones?",
    whyWeAsk: "Losses affect appetite and pricing; clean loss history helps move faster.",
  },
  {
    id: "website_or_facebook",
    label: "Website or Facebook page",
    section: "online_verification",
    type: "string",
    required: false,
    priority: 80,
    businessTypes: "everyone",
    description: "Online presence used for underwriting verification.",
    question: "Do you have a website or Facebook page? What's the link?",
    whyWeAsk: "Markets check online presence and expect it to match the submission.",
  },
];

export const FIELD_BY_ID: Record<string, FieldDefinition> = Object.fromEntries(
  GARAGE_FIELD_DEFINITIONS.map((f) => [f.id, f]),
);

export const KNOWN_FIELD_IDS: ReadonlySet<string> = new Set(
  GARAGE_FIELD_DEFINITIONS.map((f) => f.id),
);
